/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GardenOfPeaceRouteImport } from './routes/garden-of-peace'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as MemorialProductsRouteImport } from './routes/memorial-products'
import { Route as PrePlanningRouteImport } from './routes/pre-planning'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ObituariesIndexRouteImport } from './routes/obituaries/index'
import { Route as ObituariesSlugRouteImport } from './routes/obituaries/$slug'
import { Route as ObituariesCreateRouteImport } from './routes/obituaries/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenOfPeaceRoute = GardenOfPeaceRouteImport.update({
  id: '/garden-of-peace',
  path: '/garden-of-peace',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialProductsRoute = MemorialProductsRouteImport.update({
  id: '/memorial-products',
  path: '/memorial-products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrePlanningRoute = PrePlanningRouteImport.update({
  id: '/pre-planning',
  path: '/pre-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ObituariesIndexRoute = ObituariesIndexRouteImport.update({
  id: '/obituaries/',
  path: '/obituaries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObituariesSlugRoute = ObituariesSlugRouteImport.update({
  id: '/obituaries/$slug',
  path: '/obituaries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ObituariesCreateRoute = ObituariesCreateRouteImport.update({
  id: '/obituaries/create',
  path: '/obituaries/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/estimator': typeof EstimatorRoute
  '/faq': typeof FaqRoute
  '/garden-of-peace': typeof GardenOfPeaceRoute
  '/investment': typeof InvestmentRoute
  '/memorial-products': typeof MemorialProductsRoute
  '/pre-planning': typeof PrePlanningRoute
  '/services': typeof ServicesRoute
  '/obituaries/$slug': typeof ObituariesSlugRoute
  '/obituaries/create': typeof ObituariesCreateRoute
  '/obituaries/': typeof ObituariesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/estimator': typeof EstimatorRoute
  '/faq': typeof FaqRoute
  '/garden-of-peace': typeof GardenOfPeaceRoute
  '/investment': typeof InvestmentRoute
  '/memorial-products': typeof MemorialProductsRoute
  '/pre-planning': typeof PrePlanningRoute
  '/services': typeof ServicesRoute
  '/obituaries/$slug': typeof ObituariesSlugRoute
  '/obituaries/create': typeof ObituariesCreateRoute
  '/obituaries': typeof ObituariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/estimator': typeof EstimatorRoute
  '/faq': typeof FaqRoute
  '/garden-of-peace': typeof GardenOfPeaceRoute
  '/investment': typeof InvestmentRoute
  '/memorial-products': typeof MemorialProductsRoute
  '/pre-planning': typeof PrePlanningRoute
  '/services': typeof ServicesRoute
  '/obituaries/$slug': typeof ObituariesSlugRoute
  '/obituaries/create': typeof ObituariesCreateRoute
  '/obituaries/': typeof ObituariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/estimator'
    | '/faq'
    | '/garden-of-peace'
    | '/investment'
    | '/memorial-products'
    | '/pre-planning'
    | '/services'
    | '/obituaries/$slug'
    | '/obituaries/create'
    | '/obituaries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/estimator'
    | '/faq'
    | '/garden-of-peace'
    | '/investment'
    | '/memorial-products'
    | '/pre-planning'
    | '/services'
    | '/obituaries/$slug'
    | '/obituaries/create'
    | '/obituaries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/estimator'
    | '/faq'
    | '/garden-of-peace'
    | '/investment'
    | '/memorial-products'
    | '/pre-planning'
    | '/services'
    | '/obituaries/$slug'
    | '/obituaries/create'
    | '/obituaries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  EstimatorRoute: typeof EstimatorRoute
  FaqRoute: typeof FaqRoute
  GardenOfPeaceRoute: typeof GardenOfPeaceRoute
  InvestmentRoute: typeof InvestmentRoute
  MemorialProductsRoute: typeof MemorialProductsRoute
  PrePlanningRoute: typeof PrePlanningRoute
  ServicesRoute: typeof ServicesRoute
  ObituariesSlugRoute: typeof ObituariesSlugRoute
  ObituariesCreateRoute: typeof ObituariesCreateRoute
  ObituariesIndexRoute: typeof ObituariesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden-of-peace': {
      id: '/garden-of-peace'
      path: '/garden-of-peace'
      fullPath: '/garden-of-peace'
      preLoaderRoute: typeof GardenOfPeaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorial-products': {
      id: '/memorial-products'
      path: '/memorial-products'
      fullPath: '/memorial-products'
      preLoaderRoute: typeof MemorialProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-planning': {
      id: '/pre-planning'
      path: '/pre-planning'
      fullPath: '/pre-planning'
      preLoaderRoute: typeof PrePlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obituaries/': {
      id: '/obituaries/'
      path: '/obituaries'
      fullPath: '/obituaries/'
      preLoaderRoute: typeof ObituariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obituaries/$slug': {
      id: '/obituaries/$slug'
      path: '/obituaries/$slug'
      fullPath: '/obituaries/$slug'
      preLoaderRoute: typeof ObituariesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obituaries/create': {
      id: '/obituaries/create'
      path: '/obituaries/create'
      fullPath: '/obituaries/create'
      preLoaderRoute: typeof ObituariesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  EstimatorRoute: EstimatorRoute,
  FaqRoute: FaqRoute,
  GardenOfPeaceRoute: GardenOfPeaceRoute,
  InvestmentRoute: InvestmentRoute,
  MemorialProductsRoute: MemorialProductsRoute,
  PrePlanningRoute: PrePlanningRoute,
  ServicesRoute: ServicesRoute,
  ObituariesSlugRoute: ObituariesSlugRoute,
  ObituariesCreateRoute: ObituariesCreateRoute,
  ObituariesIndexRoute: ObituariesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
